sonar.projectName=${project.title}
sonar.projectKey=${project.name}
sonar.java=source>${java.version}
sonar.url=http://localhost:9000
sonar.surefire.reportsPath=target/surefire-reports
sonar.coverage=jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml
sonar.inclusions=**/services/**,**/controllers/**,**/libs/**
